image: Visual Studio 2017

environment:

  matrix:
    - platform: Win32
      configuration: Debug
      QTDIR: C:\Qt\5.11\msvc2015
      CMAKE_GENERATOR_NAME: Visual Studio 15 2017
    - platform: Win32
      configuration: Release
      QTDIR: C:\Qt\5.11\msvc2015
      CMAKE_GENERATOR_NAME: Visual Studio 15 2017
    - platform: x64
      configuration: Debug
      QTDIR: C:\Qt\5.11\msvc2017_64
      CMAKE_GENERATOR_NAME: Visual Studio 15 2017 Win64
    - platform: x64
      configuration: Release
      QTDIR: C:\Qt\5.11\msvc2017_64
      CMAKE_GENERATOR_NAME: Visual Studio 15 2017 Win64

before_build:
  - set PATH=%QTDIR%\bin;%PATH%
  - if %QTDIR:_64=%==%QTDIR% (set ARCH=x86) else (set ARCH=x64)
  - call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %ARCH%

build_script:
  - qmake qml-creative-controls.pro -r 
  - call nmake
